name: Pipeline

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: HFabi/weather
          path: ./weather
          token: ${{ secrets.GH_PAT }}
      - name: copy
        run: cp ./weather/example.txt .
      - name: print
        run: touch example.txt
